name: Build project files
on:
  push:
    branches-ignore: [project-assets]
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: hardware-${{ github.ref }}
  cancel-in-progress: true
jobs:
  publish:
    uses: crnchwrpsupreem/crnchwrpsupreem.github.io/.github/workflows/hardware-assets.yml@main
